const CompanyData = [
  {
    id: 1,
    company: "Tokopedia",
    location: "Jakarta",
    business_fields: "E-commarce",
    job_vacancie: "23",
    timeLatest: "2",
  },
  {
    id: 1,
    company: "Tokopedia",
    location: "Jakarta",
    business_fields: "E-commarce",
    job_vacancie: "23",
    timeLatest: "2",
  },
  {
    id: 1,
    company: "Tokopedia",
    location: "Jakarta",
    business_fields: "E-commarce",
    job_vacancie: "23",
    timeLatest: "2",
  },
  {
    id: 1,
    company: "Tokopedia",
    location: "Jakarta",
    business_fields: "E-commarce",
    job_vacancie: "23",
    timeLatest: "2",
  },
  {
    id: 1,
    company: "Tokopedia",
    location: "Jakarta",
    business_fields: "E-commarce",
    job_vacancie: "23",
    timeLatest: "2",
  },
  {
    id: 1,
    company: "Tokopedia",
    location: "Jakarta",
    business_fields: "E-commarce",
    job_vacancie: "23",
    timeLatest: "2",
  },
  {
    id: 1,
    company: "Tokopedia",
    location: "Jakarta",
    business_fields: "E-commarce",
    job_vacancie: "23",
    timeLatest: "2",
  },
  {
    id: 1,
    company: "Tokopedia",
    location: "Jakarta",
    business_fields: "E-commarce",
    job_vacancie: "23",
    timeLatest: "2",
  },
];

export default CompanyData;
